[project]
name = "spark-l"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
    "pyspark>=3.5.5",
    "setuptools>=80.3.1",
]

